services:
  db:
    image: mysql:8.4.6
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: secchub
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql